### ISSUE TITLE
Problem with initializers

### ISSUE THREAD

**Issue by agfa555** [omise/omise-ios-swift#4]
Hello,

I can't compile the SDK because it gives me this two errors:

'OmiseTokenRequest' cannot be constructed because it has no accessible initializers
'Omise' cannot be constructed because it has no accessible initializers

Thank you

**Comment by igroomgrim** [comment]
Has error because access control. Please let me fix. 🙏

**Comment by igroomgrim** [comment]
Fixed! Thanks! 👍

**Comment by agfa555** [comment]
OmiseTokenRequest() is fine now but Omise() still gives same error.
I'll check again tomorrow.
Thanks!!!

**Comment by igroomgrim** [comment]
Oop! So sorry that my mistake. Please try to check again.
Thanks 👍

**Comment by agfa555** [comment]
All good now.
Thanks a lot!!!!
