### ISSUE TITLE
Needed Carthage support

### ISSUE THREAD

**Issue by kittinunf** [omise/omise-ios-swift#5]
Nice for very useful library. However, I think you should add [carthage](https://github.com/Carthage/Carthage) support as well to be thorough. 

Also, I would like to see this library turns in to Omise-Swift. So, it can support Mac OS development as well.

**Comment by igroomgrim** [comment]
Work in progress and we'll update to new version kub 👍

**Comment by chakrit** [comment]
@kittinunf next version is coming with Carthage-only support krub : )
And omise-swift is on the way, too, also with day-1 Carthage support : )

No ETA yet though, there will be an announcement when we do krub.

**Comment by kittinunf** [comment]
That sounds great kub. My gut is telling me that you should not drop Cocoapods support. I think both dependency managements have pros and cons. 

Exciting for new version, I can't wait to hear from you guys.

**Comment by chakrit** [comment]
@kittinunf we're hoping you'll come help write it :p
